### PR TITLE
Use threading.Barrier to synchronize workers and main thread

### PR DESCRIPTION
**Pull request by speckulatius**
Hi there, first of all thanks for this plugin and the work you put in, it really makes testing for race conditions easier! When using it, I recently ran into cases where deadlocks between the main thread and the worker threads occurred because the `sleep` between worker initialization and `event_start.set` was too short.

So while the quick fix was to increase the sleep time, this PR suggests to use a `threading.Barrier` instead. This effectively removes the need for the main thread to "guess" how long it takes for all workers to bootstrap, but instead lets the workers "tell" the main thread when they are ready (by calling `barrier.wait`). That way we can remove all `sleep` statements and also do not need the while loop anymore.

I would be glad for any feedback and comments!

### CODE REVIEW

**Comment by idlesign** [comment]
Hi. 
Sorry for the delay. 
Thank you. Let's merge it.

--
Given that races detection by this plugin is somewhat synthetic, I'll be glad if you could describe in a few words in what cases do you use this.

**Comment by speckulatius** [comment]
Hi, thanks for merging!
I use it to test parallel sql transactions against a postgres instance to make sure my [isolation levels](https://www.postgresql.org/docs/current/transaction-iso.html) are set correctly.

Do you plan on releasing a new minor version anytime soon?

**Comment by idlesign** [comment]
> Do you plan on releasing a new minor version anytime soon?

Sure, in a couple of days.

**Comment by idlesign** [comment]
0.2.0 is out

**Pull request merged**
